# Generated by Django 4.1.7 on 2023-04-02 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='eventId',
            new_name='forEvent',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='userId',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='eventname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='tickit.event', to_field='name'),
        ),
    ]
