# Generated by Django 4.1.7 on 2023-04-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
