# Generated by Django 4.1.7 on 2023-04-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0002_rename_eventid_ticket_forevent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venueId',
            new_name='venue',
        ),
    ]
