# Generated by Django 4.1.7 on 2023-04-04 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0006_remove_venue_address_remove_venue_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='photo_url',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo_url',
            field=models.TextField(default=None, null=True),
        ),
    ]
