# Generated by Django 4.1.7 on 2023-04-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0007_event_date_event_photo_url_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
