# Generated by Django 4.1.7 on 2023-04-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0008_event_artist_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
