# Generated by Django 4.1.7 on 2023-04-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0009_alter_event_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(),
        ),
    ]
