# Generated by Django 4.1.7 on 2023-04-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0009_alter_event_venue_alter_ticket_eventname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.TextField(default='location'),
        ),
    ]
