# Generated by Django 4.1.7 on 2023-04-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0010_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.CharField(max_length=100, default=''),
        ),
    ]
