# Generated by Django 4.1.7 on 2023-04-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0011_alter_event_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artist',
        ),
    ]
