# Generated by Django 4.1.7 on 2023-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0012_remove_event_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True, default=''),
        ),
    ]
